### ISSUE TITLE
The “Okay. Let's go!” doesn’t work on macOS after manually compiling the software

### ISSUE THREAD

**Issue by LenaWil** [UltraStar-Deluxe/UltraStar-Creator#17]
![Schermafbeelding 0005-02-24 om 19 02 01](https://user-images.githubusercontent.com/6208937/221255478-7ed7af65-26dc-4c65-a45e-ff1b0592ac34.png)

When I press this button nothing happens.

**Comment by bohning** [comment]
Good news is, I can reproduce this problem. Bad news is, I don’t know why it fails. I will try to look into it when I find time.

**Comment by LenaWil** [comment]
I'm a newbie and since you have a collaborater tag and could reproduce it, does the rest of the program still work?
If so, is there a way to avoid this dialogue window?

**Comment by bohning** [comment]
Unfortunately, the bug appears elsewhere on all buttons, so getting past the intro button will not help directly. I will try to investigate the cause of this bug.

**Comment by bohning** [comment]
Please try again now after the latest commits.

**Comment by LenaWil** [comment]
I was going through my old issues, and forgot to share that this fixed it, thanks.
