### ISSUE TITLE
UltraStar Creator continues even if no audio device can be found

### ISSUE THREAD

**Issue by Profpatsch** [UltraStar-Deluxe/UltraStar-Creator#27]
https://github.com/UltraStar-Deluxe/UltraStar-Creator/blob/36e0d88565dcd28ee1ef23194d0b9db0b8326bb8/src/QUMainWindow.cpp#L51-L53

I’m trying to update USC on nixpkgs, and was bitten by this issue; the return value of `BASS_Init` is checked, but the software just continues if init fails. This will lead to an infinite loop when the first mp3 is selected, causing USC to hang.

I don’t think it makes much sense to continue initialization if the audio library fails, an error should be displayed and the program should exit instead.

**Comment by Profpatsch** [comment]
Thanks to @aszlig for debugging this!!

**Comment by DeinAlptraum** [comment]
Thank you for debugging and reporting this! This will be fixed with the next release
