### ISSUE TITLE
[UNIX version] Use UTF-8 instead of ISO-8859-1 for txt files

### ISSUE THREAD

**Issue by maxlefou** [UltraStar-Deluxe/UltraStar-Creator#5]
The program uses ISO-8859-1 format to generate files. Usually, for english songs and texts, it's not really a problem.
But for other languages (french for example) it can cause problems when using other linux programs for song edition (like Yass) with special characters such as accents. So, maybe using the UTF-8 with BOM instead would work well since UltrastarDX seems to recognize UTF-8 with BOM correctly.

Since i'm very noob at programming, i don't know at all if it's possible and how, though.

**Comment by bohning** [comment]
@maxlefou, please try the latest build after c434497f62f6714ab0ab920646650e60785ea797.

**Comment by basisbit** [comment]
please do not set UTF-8 with BOM. There is no advantage of ByteOrderMarking every text line and most standards suggest to just use UTF-8 without BOM.

**Comment by maxlefou** [comment]
utf-8 without bom doesn't support accents

**Comment by bohning** [comment]
I will have to look into this...
