### ISSUE TITLE
Can't compile: missing compact_lang_det.h

### ISSUE THREAD

**Issue by jmfergeau** [UltraStar-Deluxe/UltraStar-Creator#51]
```
QUMainWindow.cpp:31:10: fatal error: compact_lang_det.h: No such file or directory
```

Indeed, I couldn't find it in sources. cld2 is installed in the system though.

Thanks.

**Comment by DeinAlptraum** [comment]
We previously included the entire cld2 code in the repo and recently changed that to a submodule, so make sure you're pulling submodules as well. Then this will work as usual
