### ISSUE TITLE
error compilation on Ubuntu 17.10

### ISSUE THREAD

**Issue by legluondunet** [UltraStar-Deluxe/UltraStar-Creator#7]
Hello,
I obtain this error when I tried to compile it on Ubuntu 17.10:

`$ make
...
g++ -m64 -Wl,-rpath,'$ORIGIN/lib' -Wl,-O1 -o ../bin/release/UltraStar-Creator tmp/release/main.o tmp/release/QUMainWindow.o tmp/release/QU.o tmp/release/QUAboutDialog.o tmp/release/QUMessageBox.o tmp/release/QULogService.o tmp/release/QURibbonBar.o tmp/release/QUMonty.o tmp/release/QUMontyArea.o tmp/release/QUSongSupport.o tmp/release/QUSongLine.o tmp/release/QUSongFile.o tmp/release/QUSongDatabase.o tmp/release/QUStringSupport.o tmp/release/qrc_UltraStar-Creator.o tmp/release/moc_QU.o tmp/release/moc_QUMainWindow.o tmp/release/moc_QUAboutDialog.o tmp/release/moc_QUMessageBox.o tmp/release/moc_QULogService.o tmp/release/moc_QURibbonBar.o tmp/release/moc_QUMontyArea.o tmp/release/moc_QUSongSupport.o tmp/release/moc_QUSongLine.o tmp/release/moc_QUSongInterface.o tmp/release/moc_QUSongFile.o tmp/release/moc_QUSongDatabase.o tmp/release/moc_QUStringSupport.o   -L/usr/X11R6/lib64 -L../lib/unix -lbass -lbass_fx -ltag -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld : escamotage incompatible ../lib/unix/libbass.so lors de la recherche de -lbass
/usr/bin/ld : ne peut trouver -lbass
collect2: error: ld returned 1 exit status
Makefile:218 : la recette pour la cible « ../bin/release/UltraStar-Creator » a échouée
make: *** [../bin/release/UltraStar-Creator] Erreur 1
`

Thank you for your help.

**Comment by bohning** [comment]
Hi,

you seem to be compiling for a 64-bit target, the provided libbass.so seems to be 32-bit. You can either try to compile for a 32-bit target or replace the libbass.so with its 64-bit version from [here](http://www.un4seen.com/download.php?bass24-linux)

**Comment by bohning** [comment]
@legluondunet, please try again after an update. I now included the x64 versions of the BASS libraries, it should compile on Ubuntu with these changes.

**Comment by legluondunet** [comment]
Hello,
I just tried to compile the last UltraStar-Creator version on Ubuntu 18.04 and the compilation passed without error.
Thank you!

**Comment by bohning** [comment]
Good news, thanks for the feedback.
